package com.zatsepinvl.activityplay.multiplayer.room.storage

import com.zatsepinvl.activityplay.multiplayer.room.model.MultiplayerRoomState
import com.zatsepinvl.activityplay.multiplayer.storage.RealtimeStorage

interface MultiplayerRoomStateStorage: RealtimeStorage<MultiplayerRoomState>